### ISSUE TITLE
项目中是否没有libeasypr工程？

### ISSUE THREAD

**Issue by bolong2016** [livezingy/EasyPR_MFC#1]
作者你好啊，我下载你的的代码后无法加载libeasypr的项目。你提供的工程是否要另外下载原作的easypr进行编译？

**Comment by bolong2016** [comment]
http://www.voidcn.com/article/p-dapqdmvj-wp.html

**Comment by livezingy** [comment]
您好，项目中包含libeasypr工程，不需要另外下载原作者的easypr进行编译。如果方便的话，请截取更详细的错误信息，我看看是否能帮助您。
